---
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Space Junk
description: Help the Scratch mascot avoid the space junk and return safely back to
  Earth!
original_url: https://codeclubprojects.org/en-GB/scratch/space-junk
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Controlling the cat
- title: 'Challenge: More movement'
- title: Space junk!
- title: 'Challenge: Changing your planet''s orbit'
- title: Getting back to Earth
- title: 'Challenge: More space junk'
- title: 'Challenge: 2 players'

