hero_image: images/space-junk.png
theme: yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Space Junk
description: Help the Scratch mascot avoid the space junk and return safely back to Earth!
original_url: https://codeclubprojects.org/en-GB/scratch/space-junk
interests: space
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Controlling the cat
- title: 'Challenge: More movement'
- title: Space junk!
- title: 'Challenge: Changing your planet''s orbit'
- title: Getting back to Earth
- title: 'Challenge: More space junk'
- title: 'Challenge: 2 players'
